/etc/apache2/sites-available/autodeluxegarage.es.conf

<VirtualHost *:80>
        ServerName autodeluxegarage.es
        ServerAlias www.autodeluxegarage.es
        Redirect permanent / https://autodeluxegarage.es/
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost *:443>

        ServerName autodeluxegarage.es
	ServerAlias www.autodeluxegarage.es
        ServerAdmin info@autodeluxegarage.es
        DocumentRoot /var/www/autodeluxegarage.es/build

        ErrorLog /var/www/autodeluxegarage.es/logs/error.log
        CustomLog /var/www/autodeluxegarage.es/logs/access.log combined

        Include /etc/letsencrypt/options-ssl-apache.conf
        SSLCertificateFile /etc/letsencrypt/live/autodeluxegarage.es/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/autodeluxegarage.es/privkey.pem

        <Directory /var/www/autodeluxegarage.es/build>
		RewriteEngine On
		RewriteCond %{REQUEST_URI} !\.(jpg|jpeg|png)$ [NC]
		RewriteCond %{REQUEST_FILENAME} !-f
		RewriteCond %{REQUEST_FILENAME} !-d
		RewriteRule ^ index.html [L]
        </Directory>

</VirtualHost>
</IfModule>
